### PR TITLE
Refactored progress bar and added option to sleep if its working hours-MANU-5609

### PR DESCRIPTION
**Pull request by rderik**
**Jira Issue:** MANU-5609

**Changes proposed in this pull request:**

 + Refactor progress bar
 + Added support methods to schedule a script to run

**Details of the implementation:**

Moved the code that was being used to prevent the script from running during
working hours to progress bar, it might be better in another area but
because they are currently used together the functionality was bundled
together.

### CODE REVIEW

**Comment by amontano** [comment]
Convertiste los metodos wait_if_business_hours, etc. en metodos de instancia. Yo los conservaria como metodos de clase. El "extend ActiveSupport::Concern" soporta eso.

**Comment by rderik** [comment]
Ok, tendriamos que pensar donde poner el initializer:
```
    def initialize
      self.output = STDERR.tty? ? STDERR : STDOUT
      self.reset_progress_bar
    end
```

**Comment by amontano** [comment]
Creo que estas hablando de otros metodos. Los metodos que jalaste de Flare son los que serian de clase: self.wait_if_business_hours(daylight), y como private: self.now, self.start_time y self.end_time.

Los metodos que ya estaban que si dependen de atributos del objeto si serian metodos de instancia: initialize, say(msg), reset_progress_bar, update_progress_bar(bar:, valid_point:, num_errors:) y progress_bar(num:, total:, current:)

**Comment by rderik** [comment]
Ah correcto, tenes razon. Ok, los corrigo cuando regrese y te escribo para que lo revisemos.

**Pull request merged**
